Parameters:
  InstanceVpcId:
    Type: AWS::EC2::VPC::Id
    Description: "The ec2 instance network interface vpc id"
  InstanceSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: "The ec2 instance network interface subnet id "
  InstanceAmi:
    Type: String
    Description: "The ec2 instance image id"
Resources:
  myWebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our test host
      VpcId: 
        Ref: InstanceVpcId
      SecurityGroupIngress: 
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          FromPort: -1
          ToPort: -1

  myWebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref InstanceAmi
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - Ref: "myWebAccessSecurityGroup"
          SubnetId: !Ref InstanceSubnetId
      UserData:
            Fn::Base64: !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd
              systemctl start httpd
        
      